name: release-qa

on:
  push:
    branches: [ qa ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: git config --global user.name GitHubAction
    - run: git config --global user.email GitHubAction@freecast.com  
    - run: npm run release -- minor --ci
    - run: git checkout develop
    - run: git merge qa && git push
